[versions]
agp = "8.13.0"

# testing
junit = "4.13.2"
androidx-junit = "1.3.0"
espresso = "3.7.0"

# ui
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
drawerlayout = "1.2.0"

# firebase
firebase-bom = "34.5.0"

# images
glide = "5.0.5"
picasso = "2.71828"

# auth / credentials
credentials = "1.5.0"
googleid = "1.1.1"

# networking
retrofit = "3.0.0"
okhttp-logging = "5.3.0"

# tikxml
tikxml = "0.8.15"

# algolia
algolia = "3.27.0"

[libraries]
# ui
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
activity = { module = "androidx.activity:activity", version.ref = "activity" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawerlayout" }

# firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }

# images
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }

# auth / credentials
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials-play = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }

# networking
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-logging" }

# tikxml
tikxml-core = { module = "com.tickaroo.tikxml:core", version.ref = "tikxml" }
tikxml-annotation = { module = "com.tickaroo.tikxml:annotation", version.ref = "tikxml" }
tikxml-converter = { module = "com.tickaroo.tikxml:retrofit-converter", version.ref = "tikxml" }
tikxml-processor = { module = "com.tickaroo.tikxml:processor", version.ref = "tikxml" }

# algolia
algolia = { module = "com.algolia:algoliasearch-android", version.ref = "algolia" }

# tests
junit = { module = "junit:junit", version.ref = "junit" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
